#use_frameworks!
source 'https://github.com/ZeroDelegate/CXCommonSpec'
platform :ios, '10.0'

target 'CXDeviceListKit_Example' do
  pod 'CXDeviceListKit', :path => '../'

  pod 'CXCommonKit'
  
  target 'CXDeviceListKit_Tests' do
    inherit! :search_paths

    
  end
end
